### PR TITLE
The Next Web page clon

### PR DESCRIPTION
**Pull request by bertil291utn**
**We have achieved the whole page.**
- Navbar section 
- Hero section articles
- Latest News section 
- Footer section

All features where write as responsive design as the project was introduced
Please open to receive any suggestions.  💻🚀

### CODE REVIEW

**Comment by lekegitrepo** [comment]
### Hi @bertil291utn  and @Maclenn77  :smile_cat: :smile_cat:
### Your project looks great and I think you have done a good job. However, you still need to make some required changes:

### :v: section: The Navigation bar
####  - large screen  ✔️ 
#### - medium screen ✔️ 
####  - small screen ✔️ 

### :v: section: Top 3 articles
####  - large screen  ✔️ 

### - medium screen ❌ 
#### At the medium screen you page behave differently from the original:

  **_This is your page at 768px:_**
   
image

  **_This is the original:_**

image


####  - small screen ✔️ 

### :v: section: Latest news
###  - large screen  ❌ 
  #### The page suppose to display four-column on a large screen: 1024px, 1440px

  **_This is your page:_**
  
image

**_This is the original: 1024px_**

image


#### - medium screen ❌ 

**_This is your page at 768px_**

image

**_This is the original page at 768px_**

image


####  - small screen ✔️ 

### :v: section: Latest Funding
####  - large screen  ✔️ 
#### - medium screen ❌ 

 **_This is your page at 768px_**

image

**_This is the original page at 768px_**

image


####  - small screen ✔️ 

### :v: section: Categories (Apps, Gear, Tech, etc)
####  - large screen  ✔️ 
### - medium screen ✔️ 

 **_This is your page at 768px_**

image


**_This is the original page at 768px_**

image


####  - small screen ✔️ 

### :v: section: Latest deals section
####  - large screen  ❌ 
 **_The page should display four column at 1024px screen size and above_**

**_This is your page:_**

image

**_This is the original:_**

image


#### - medium screen ❌ 

 **_This is your page at 768px_**

image

**_This is the original page at 768px_**

image


####  - small screen ✔️ 

### :v: section: Footer
####  - large screen  ✔️ 
#### - medium screen ✔️ 
####  - small screen ✔️ 

### Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) and [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/align_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))

**_I think float is missing from your style rules._**

**_Kindly, make the required changes and submit for review._**

**_If you have any doubt or question contact me on slack_**

### Reviewed by: Temitayo Adeleke

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require Changes

**Comment by Maclenn77** [comment]
Hi, @lekegitrepo: 

Thank you for your time reviewing this project. Required changes has been done.

About the three columns in Last News and Last Deals section displayed at large screen (1024), we didn't find that problem. I send a screenshot.

Captura de pantalla de 2020-03-14 00-36-56

Have a nice weekend.

**Review by mosesogwo — APPROVED** [review]
**Good work making the requested changes :+1:. Your project is approved :heavy_check_mark:**

You can now merge and move ahead.

**Cheers:stars:**

### Status: Approved!

**Pull request merged**
